# Generated by Django 4.1 on 2022-08-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_rename_uid_url_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='link',
            field=models.CharField(max_length=100000),
        ),
    ]
